# This is a basic workflow to help you get started with Action
name: Run AOC2020 Solutions

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # setup haxe and print version
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.4
      - run: |
          haxe -version
          haxelib install hxnodejs

      # run solutions
      - name: '[interp] Advent Of Code 2020 Solutions'
        run: |
          haxe interp.hxml

      - name: '[js] Advent Of Code 2020 Solutions'
        run: |
          haxe build/js.hxml
          node bin/main.js
        if: always()

      - name: '[neko] Advent Of Code 2020 Solutions'
        run: |
          haxe build/neko.hxml
          neko bin/main.n
        if: always()

      - name: '[php] Advent Of Code 2020 Solutions'
        run: |
          haxe build/php.hxml
          php bin/php/index.php
        if: always()

      - name: '[cs] Setup hxcs'
        run: |
          haxelib install hxcs
        if: always()
      - name: '[cs] Advent Of Code 2020 Solutions'
        run: |
          haxe build/cs.hxml
          bin/cs/bin/Main.exe
        if: always()

      - name: '[java] Setup hxjava'
        run: |
          haxelib install hxjava
        if: always()
      - name: '[java] Advent Of Code 2020 Solutions'
        run: |
          haxe build/java.hxml
          java -jar bin/java/Main.jar
        if: always()

      - name: '[jvm] Advent Of Code 2020 Solutions'
        run: |
          haxe build/jvm.hxml
          java -jar bin/jvm/Main.jar
        if: always()

      - name: '[cpp] Setup hxcpp'
        run: |
          haxelib install hxcpp
        if: always()
      - name: '[cpp] Compile'
        run: |
          haxe build/cpp.hxml
        if: always()
      - name: '[cpp] Advent Of Code 2020 Solutions'
        run: |
          bin/cpp/Main
        if: always()
